name = "Bilinear"
uuid = "b4b11043-bca8-43d4-9f2c-54842c74f03c"
authors = ["Dongdong Kong <kongdd@users.noreply.github.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
SpatRasters = "25a4c9b9-c310-4d6e-b9a7-fa79274760a1"

[sources]
SpatRasters = {url = "https://github.com/jl-pkgs/SpatRasters.jl"}

[compat]
LinearAlgebra = "1.11.0"
NearestNeighbors = "0.4.22"
SpatRasters = "0.1.3"
